server:
  port: 10001
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: algorithm
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    default-property-inclusion: non_null


